# Generated by Django 2.1.2 on 2018-10-19 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat_Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='chat',
            name='room_name',
        ),
        migrations.AlterField(
            model_name='chat',
            name='write_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='chat',
            name='chat_room',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='chat.Chat_Room'),
        ),
    ]
